version: '3'
services:
  app:
    build:
      context: .
    
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/workout_app
      - public-data:/workout_app/public
      - tmp-data:/workout_app/tmp
      - log-data:/workout_app/log
    depends_on:
      - db
  db:
    image: mysql:8.0
   
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/workout_app/public
      - tmp-data:/workout_app/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  log-data:
  db-data: